Repository TeamEpochGithub/agogos, pull requests merged in 2024-04, with the labels that each got.

#60 Add type class to both training and transforming and update classes t…
  agogos/training.py
  agogos/transforming.py
  tests/test_transforming.py
Labels: 02 - Refactor

#61 V0.3.3
  agogos/_core.py
  agogos/training.py
  agogos/transforming.py
  pyproject.toml
  tests/test_transforming.py
Labels: 06 - Release

#67 Fix bug with copying data in parallelsystems
  agogos/training.py
  agogos/transforming.py
  tests/test_transforming.py
Labels: 00 - Bug

#68 V0.3.4
  agogos/training.py
  agogos/transforming.py
  pyproject.toml
  tests/test_transforming.py
Labels: 06 - Release

#75 BUG: Order of steps in parallel system changes hash
  README.md
  agogos/_core.py
  agogos/training.py
  agogos/transforming.py
  tests/test_training.py
  tests/test_transforming.py
Labels: 00 - Bug

#77 Add weighs to parallel system
  agogos/_core.py
  agogos/training.py
  agogos/transforming.py
Labels: 02 - Refactor

#78 V0.4
  README.md
  agogos/_core.py
  agogos/training.py
  agogos/transforming.py
  pyproject.toml
  tests/test_training.py
  tests/test_transforming.py
Labels: 06 - Release
